version: '3.4'

services:
  qpanc.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - DEFAULT_CONNECTION=Server=qpanc.database;Port=5432;Database=postgres;User Id=postgres;Password=keepitsupersecret;
      - JWTBEARER_VALIDISSUER=https://api.qpanc.tobiasmesquita.dev/
      - JWTBEARER_VALIDAUDIENCE=https://api.qpanc.tobiasmesquita.dev/
      - JWTBEARER_ISSUERSIGNINGKEY=itUXC7iVRsofSDWNeg/aLYpc4bMzHAsMPzeItE1PQi2tMK2f4t0InRgTE5B/4IAjhAX5LQSIGL1CaUHSSzED8A==
      - JWTBEARER_TOKENDECRYPTIONKEY=7hfboHG0d4GnXjVng0ukMo+IgrKKrPLUMtOvnt4S514=
      - CORS_HOSTS__0=qpanc.tobiasmesquita.dev
    ports:
      - "34512:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  qpanc.app:
    container_name: qpanc_app_prod
    build:
      context: ./QPANC.App
      target: 'prod-stage'
      dockerfile: .docker/prod.Dockerfile
    volumes:
      - webapp:/app
    ports:
      - "34515:3000"

  qpanc.database:
    volumes:
      - database:/var/lib/postgresql/database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: keepitsupersecret
      POSTGRES_DB: postgres

volumes:
  webapp:
  database:
  